name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Шаг 3: Сборка Docker образа
      - name: Build Docker image
        run: |
          docker build -t kaiyrzhan/kaiyrzhan:latest .

      # Шаг 4: Публикация Docker образа в Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push kaiyrzhan/kaiyrzhan:latest
